# Generated by Django 4.1.6 on 2023-02-10 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
        ("traits", "0002_remove_trait_pets"),
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="traits",
            field=models.ManyToManyField(related_name="pets", to="traits.trait"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pet",
                to="groups.group",
            ),
        ),
    ]
