# Generated by Django 4.1.6 on 2023-02-10 23:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_pet_traits_alter_pet_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="traits",
        ),
    ]
