# Generated by Django 4.1.6 on 2023-02-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0004_remove_trait_pets"),
        ("pets", "0004_alter_pet_group_alter_pet_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="traits",
            field=models.ManyToManyField(related_name="pets", to="traits.trait"),
        ),
    ]
